---
inventory:
    plugin: YAMLInventory
    options:
        host_file: '/mnt/c/NornirJunos/hosts/hosts.yml'
        group_file: '/mnt/c/NornirJunos/groups/groups.yml'
        defaults_file: '/mnt/c/NornirJunos/defaults/defaults.yml'

runner:
    plugin: threaded
    options:
        num_workers: 10