---

vMX-PE1:
    hostname: 10.10.21.121
    groups:
        - junos_group
    data:
        node_type: 'PE'
        mc_lag: True
        mc_lag_int: 'ge-0/0/1'
        mc_conf:
            mode: 'active-standby'
            control: 'active'
            chassis_id: '0'
        lacp_conf:
            sys_id: 64:0e:94:28:02:c0
            admin_key: 1
        iccp_conf:
            local_ip: '6.6.6.6'
            peer_ip: '3.3.3.3'
        cust_vlans:
            vlan_id: 500

vMX-PE2:
    hostname: 10.10.21.174
    groups:
        - junos_group
    data:
        node_type: 'PE'
        mc_lag: True
        mc_lag_int: 'ge-0/0/1'
        mc_conf:
            mode: 'active-standby'
            control: 'standby'
            chassis_id: '1'
        lacp_conf:
            sys_id: 64:0e:94:28:02:c0
            admin_key: 1
        iccp_conf:
            local_ip: '3.3.3.3'
            peer_ip: '6.6.6.6'
        cust_vlans:
            vlan_id: 500